x-app: &app
  build: .
  image: bengriff1/zoopla-bridge:latest
  volumes:
    - .:/code
  command: "poetry run gunicorn --bind 0.0.0.0:5300 --reload --log-level debug zoopla_bridge.app:app"

services:
  web:
    <<: *app
    ports:
      - "5300:5300"
    stop_signal: SIGINT
  funtest:
    <<: *app
    command: echo "Done"
    depends_on:
      - web
