apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init"
  annotations:
    "helm.sh/hook": post-upgrade
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- toYaml .Values.env | nindent 12 }}
          command: ["poetry", "run", "alembic", "upgrade", "head"]
      restartPolicy: Never
