openapi: "3.0.0"
info:
  title: Bridge Template
  description: API description in Markdown.
  version: 1.0.0
tags:
  - name: health
  - name: search
paths:
  /health:
    get:
      summary: Returns ok.
      tags:
        - health
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                  - ok
  /v1/search/properties:
    post:
      summary: Do search
      tags:
        - search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: object
      responses:
        200:
          description: Search response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Result"
        400:
          description: Invalid request
components:
  schemas:
    Result:
      allOf:
        - type: object
          properties:
            result_id:
              $ref: "#/components/schemas/uuid"
            values:
              type: array
              items:
                $ref: "#/components/schemas/Value"
              minItems: 1
          required:
            - result_id
            - values
        - $ref: "#/components/schemas/Immutable"

    Value:
      type: object
      properties:
        field_id:
          type: string
          enum: [field1, field2, field3]
        value:
          type: string
      required:
        - field_id
        - value

    Immutable:
      type: object
      properties:
        created_at:
          readOnly: true
          allOf:
            - type: string
              format: date-time
      required:
        - created_at

    uuid:
      type: string
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
