openapi: "3.0.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
paths:
  /health:
    get:
      summary: Returns ok.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  db:
                    type: boolean
                required:
                  - ok
                  - db
