"""init

Revision ID: 663c218a16e1
Revises:
Create Date: 2021-03-17 23:57:27.674986

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "663c218a16e1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
